### ISSUE TITLE
Crops won't grow

### ISSUE THREAD

**Issue by fluxionary** [acmgit/cucina_vegana#5]
I'm using a recent version of TenPlus1's farming_redo, and for some reason, the cucina_vegana crops have stopped growing from seeds. More accurately, the planted "seed" item doesn't properly turn into a stage-1 plant; if I bonemeal the seed, or spawn in a stage-n plant, it works though. I'm not sure if it's due to a change in cucina vegana or farming_redo itself, I was curious if you're seeing similar behaviour. 

To test, all you should need are the default mods from minetest_game, farming_redo, and cucina_vegana.

**Comment by acmgit** [comment]
What is the setting cucina_vegana.plant_settings.germ_launch in your configuration?
If you have TenPlus1's farming_redo installed, you have to set this value to 1.

I know this behavior, this is the reason, why cucina_vegana is splitted into farming and farming_redo mod.
The mod check's itself, is farming_redo installed, it switches automatically to the redo_mod, but it does not for the cucina_vegana.plant_settings.germ_launch-setting.

I've added this setting, because in the normal farming-mode, it's possible to set the setting to zero, which means, it starts as seed.
Default and if you don't set it, it is 0.

Maybe this is the solution for your Problem.
Greetings, Clyde.

**Comment by fluxionary** [comment]
Fantastic! That fixes it. You should perhaps automatically set the correct default when farming_redo is installed, or at least document that this needs to be done.

**Comment by acmgit** [comment]
I'm glad, that i could help you.
The correct value should be 0, because the mod should be compatible with default farming.
I added this setting for exactly your case, because maybe there is a config with farming_redo, that works with the setting of 0 too, i haven't tested it.

Greetings, Clyde.
